[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agrifund = "9RVR31qnjswGMc4fYHpdNK5xxUsN2oxf5YfUB6ErxP7B"

[programs.localnet]
agrifund = "9RVR31qnjswGMc4fYHpdNK5xxUsN2oxf5YfUB6ErxP7B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "G7q4wCAJ422kER19HKbDJ23vSJ3nzcJ1FnZG3yGgwnnL"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"
